---
- name: win_reboot module Playbook  run:ansible-playbook -i inventory.yml reboot.yml
  hosts: 192.168.200.160
  become: false
  gather_facts: false
  tasks:
    - name: reboot host(s)
      ansible.windows.win_reboot:
        msg: "reboot by Ansible"
        pre_reboot_delay: 5
        post_reboot_delay: 10
