---
- name: Uninstalling ZOOM
  hosts: all

  tasks:
#    - name: Download the ZOOM installer - In case the MSI is not on the computer
#      win_get_url:
#        url: https://zoom.us/client/latest/ZoomInstallerFull.msi
#        dest: c:\ansible\ZoomInstallerFull.msi

    - name: Uninstall MSI
      win_package:
        path: C:\ansible\ZoomInstallerFull.msi
        state: absent
